const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
    windowMinimize: () => ipcRenderer.send('window-minimize'),
    windowMaximize: () => ipcRenderer.send('window-maximize'),
    windowClose: () => ipcRenderer.send('window-close'),
    openMain: (sessionJson) => ipcRenderer.send('open-main', sessionJson),
    launchGame: (settings) => ipcRenderer.send('launch-game', settings),
    onLauncherStatus: (cb) => ipcRenderer.on('launcher-status', (_e, v) => cb(v)),
    msLogin: () => ipcRenderer.send('ms-login'),
    onMsLogin: (cb) => ipcRenderer.on('ms-login-reply', (_e, v) => cb(v)),
    getVersions: () => ipcRenderer.invoke('get-versions'),
    searchMods: (opts) => ipcRenderer.invoke('search-mods', opts),
    downloadMod: (opts) => ipcRenderer.invoke('download-mod', opts),
    onDownloadProgress: (cb) => ipcRenderer.on('download-progress', (_e, v) => cb(v)),
    onSession: (cb) => ipcRenderer.on('session-data', (_e, v) => cb(v)),
    onUpdateAvailable: (cb) => ipcRenderer.on('update_available', () => cb()),
    onUpdateDownloaded: (cb) => ipcRenderer.on('update_downloaded', () => cb()),
    onUpdateNotAvailable: (cb) => ipcRenderer.on('update_not_available', () => cb()),
    restartApp: () => ipcRenderer.send('restart_app'),
    checkUpdates: () => ipcRenderer.send('check_updates'),
    applySkin: (opts) => ipcRenderer.invoke('apply-skin', opts),
});